### ISSUE TITLE
Issues with Grader Scales

### ISSUE THREAD

**Issue by patriclougheed** [humanage/moodle-mod_eduplayer#4]
"Field "grade" does not exist in table "eduplayer""

I receive this error when trying to add scales to the grade book and removing eduplayer install allows me to create scales again.

This occurs in Moodle 2.6.1

**Comment by sharpchi** [comment]
Very strange. I just got exactly the same message doing the same thing in Moodle 2.6.0.

**Comment by sharpchi** [comment]
If you don't need grade support for eduplayer, this code change will get you working again.
https://github.com/sharpchi/moodle-mod_eduplayer/commit/dddd93c37b63f93add55c6746569cef825aaaf11
